### ISSUE TITLE
Support for transformers

### ISSUE THREAD

**Issue by dgaw** [leshow/i3ipc#1]
Thanks for the library, @leshow! Finally we can transform i3 into xmonad.

Seriously though. I've been playing around with the library and I had to extend it a bit in order to use it with transformers on top of IO.

I've added the following variant of `subscribe` to the library:
```
subscribe' :: MonadIO m => (Either String Evt.Event -> m ()) -> [Sub.Subscribe] -> m ()
```

I'm happy to send a PR with this change.

**Comment by leshow** [comment]
Absolutely! I'm happy to accept PRs, send away!

**Comment by leshow** [comment]
Looking through the original code, perhaps it would be nice to provide alternate parameterized functions for every function that uses `IO`, or just change the existing ones to `MonadIO` as a breaking change.

**Comment by dgaw** [comment]
@leshow I agree it would be nice to have MonadIO versions of all the IO functions but personally I don't mind a bit of lift'ing in my client code as long as it does what I want it to do. If you do introduce this as a breaking change I won't protest though. :)

I've just sent a PR request for subscribe'.

**Comment by leshow** [comment]
I'm going to leave this issue open, I want to add 'full' support for transformers in a breaking change at some point.

**Comment by leshow** [comment]
Okay, all done! It should be on hackage as version `0.1.0.1`.

**Comment by dgaw** [comment]
Good stuff, thanks!

**Comment by leshow** [comment]
Everything is ported away from `IO` and using `MonadIO`, `MonadThrow` etc. Closing. Haven't published on hackage yet
