### ISSUE TITLE
Sway compatibility?

### ISSUE THREAD

**Issue by simvux** [leshow/i3ipc#3]
I'm trying to use this library on sway and while most functionality works, it doesn't seem fully compatible as getting Window events seems to crash. Is it supposed to be compatible with sway? Afaik the API is super similar so if not it wouldn't be to difficult to port.

**Comment by leshow** [comment]
For some reason I didn't get an email about this. Yeah, we absolutely can support sway, afaik it just uses an environment var to grab the initial socket port. All of the IPC messages are exactly the same, so this should be like a 1 or 2 line change

**Comment by leshow** [comment]
Here it is,
https://www.mankier.com/1/sway#SWAYSOCK_1

You'll notice [here](https://github.com/leshow/i3ipc/blob/master/src/I3IPC.hs#L92) we use `I3SOCK`. We just need a similar method that gets the var from `SWAYSOCK` instead. 

I don't have sway so I can't test this, would you like to add this function and send a PR? If you could,  please try all the `getX` functions and a `subscribe` in ghci also, just to double check sway is giving back a compatible response. I'm 90% sure sway is api compatible with i3, but I'd feel better if someone actually tried.

**Comment by simvux** [comment]
Sure I could probably do that, (although I'm admittedly not that great at Haskell). 
I think there's also some functionality in Sway that isn't implemented in i3, but don't quote me on that. 

There's also a few bugs in I've discovered, for example I3IPC/Reply.hs:335 is missing a "none" field which causes it to crash for me.

**Comment by leshow** [comment]
Can you paste the error? We could add a catch all for each of the cases
instead of the panic, arguably throwing an exception there isn't the best
idea.

It's possible sway does have some extra features, but they do advertise i3
compatibility. I wouldn't be against adding some of sways features behind
some kind of conditional compilation.

**Comment by leshow** [comment]
If you could get a json dump of any serializations that fail that would be great. I haven't been able to find anything missing yet.

**Comment by simvux** [comment]
I'm currently busy with other projects but if I need to script something with sway I'll make sure to do it through i3ipc so I can troubleshoot potential issues and detect missing features in the process
